services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: whereg
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_URL: jdbc:mysql://db:3306/whereg?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis

volumes:
  mysql-data: