name: Backend Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Navigate to project
      run: |
        cd ~/app/backend

    - name: Restart Application
      run: |
        cd ~/app/backend
        
        CURRENT_PID=$(pgrep -f 'whereG.*\.jar')
        if [ -z "$CURRENT_PID" ]; then
            echo "No running spring boot application found."
        else
            echo "Killing running application with PID: $CURRENT_PID"
            kill -15 $CURRENT_PID
            sleep 5
        fi
        
        nohup java -jar ~/app/backend/build/libs/*.jar > nohup.out 2>&1 &