name: Backend Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest code
      run: |
        cd ~/app/backend
        git pull origin master

    - name: Deploy and Restart Server
      run: |
        cd ~/app/backend
        
        # 원래 구동 중이던 자바(Spring Boot) 프로그램 번호를 찾아서 안전하게 끕니다.
        CURRENT_PID=$(pgrep -f 'whereG.*\.jar')
        if [ -z "$CURRENT_PID" ]; then
            echo "No running spring boot application found."
        else
            echo "Killing running application with PID: $CURRENT_PID"
            kill -15 $CURRENT_PID
            sleep 5
        fi
        
        nohup java -jar build/libs/*.jar > nohup.out 2>&1 &